#spring:
#   application:
#    name: sharding-jdbc
#   datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
#    url: jdbc:mysql://localhost:3306/test_01?useUnicode=true&characterEncoding=utf8&useSSL=false              # 数据库名称
#    username: root
#    password: root
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
#
#
#--------------mybatis配置----------------
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml         # mybatis配置文件所在路径
  type-aliases-package: com.example.shardingsphere.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                        # mapper映射文件

##-------------读写分离配置----------------
sharding:
  jdbc:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.43.219:3310/ds_0?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        dbcp2:
          max-wait-millis: 200
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.43.219:3311/ds_0?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.43.219:3312/ds_0?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        name: dataSource
        master-data-source-name: master
        slave-data-source-names: slave0,slave1







